export const genreViToEn: Record<string, string> = {
  "hành động": "Action",
  "phiêu lưu": "Adventure",
  hài: "Comedy",
  "nghệ thuật tiên phong": "Avant Garde",
  "bí ẩn": "Mystery",
  "chính kịch": "Drama",
  ecchi: "Ecchi",
  "giả tưởng": "Fantasy",
  hentai: "Hentai",
  "kinh dị": "Horror",
  "lãng mạn": "Romance",
  "khoa học viễn tưởng": "Sci-Fi",
  "tình cảm đồng giới nữ": "Girls Love",
  "tình cảm đồng giới nam": "Boys Love",
  "thể thao": "Sports",
  "cuộc sống thường nhật": "Slice of Life",
  "siêu nhiên": "Supernatural",
  "hồi hộp": "Suspense",
  "đạt giải thưởng": "Award Winning",
  "ẩm thực": "Gourmet",
  "tình dục": "Erotica",
};
